### ISSUE TITLE
DESK MINI 可用 睡眠勾选下？

### ISSUE THREAD

**Issue by SnailDove** [Jimmuy/Hackintosh-Deskmini-H310#1]
"**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂

**Comment by Jimmuy** [comment]
> "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂

在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的

**Comment by SnailDove** [comment]
> > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> 
> 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的

对的 跟你一样**差别**就是：硬盘海康威视，i5 8500，内存威刚，散热猫扇

第一次装黑果，完全都不懂，就是把你仓库这个底下所有文件夹，替换我的efi就行了是吧？

**Comment by SnailDove** [comment]
> > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> 
> 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的

我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯

**Comment by Jimmuy** [comment]
> > > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> > 
> > 
> > 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的
> 
> 我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯

我就是用的小兵的15.2的镜像，就在他的博客可以下的到的

**Comment by SnailDove** [comment]
> > > > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> > > 
> > > 
> > > 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的
> > 
> > 
> > 我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯
> 
> 我就是用的小兵的15.2的镜像，就在他的博客可以下的到的

好的，谢谢你的反馈，对于睡眠唤醒后屏幕不亮问题（其他都正常），有什么好的建议，或者可能的解决方向去探索吗？ @Jimmuy  有deskmini的机友群吗，嘻嘻？

**Comment by Jimmuy** [comment]
> > > > > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> > > > 
> > > > 
> > > > 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的
> > > 
> > > 
> > > 我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯
> > 
> > 
> > 我就是用的小兵的15.2的镜像，就在他的博客可以下的到的
> 
> 好的，谢谢你的反馈，对于睡眠唤醒后屏幕不亮问题（其他都正常），有什么好的建议，或者可能的解决方向去探索吗？ @Jimmuy 有deskmini的机友群吗，嘻嘻？

没有群，我也是一个人折腾的，你说的不亮的问题好像我也遇到了，不过我忘记怎么解决的了，你试试hdmi接口和dp接口拔下来再插上去行不行，好像网上可以找到解决方法，你可以找找

**Comment by SnailDove** [comment]
> > > > > > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> > > > > 
> > > > > 
> > > > > 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的
> > > > 
> > > > 
> > > > 我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯
> > > 
> > > 
> > > 我就是用的小兵的15.2的镜像，就在他的博客可以下的到的
> > 
> > 
> > 好的，谢谢你的反馈，对于睡眠唤醒后屏幕不亮问题（其他都正常），有什么好的建议，或者可能的解决方向去探索吗？ @Jimmuy 有deskmini的机友群吗，嘻嘻？
> 
> 没有群，我也是一个人折腾的，你说的不亮的问题好像我也遇到了，不过我忘记怎么解决的了，你试试hdmi接口和dp接口拔下来再插上去行不行，好像网上可以找到解决方法，你可以找找

我就是这么用的，重新对屏幕进行开关机就可以了，谢谢啦，如果我有找到组织把你拉进去

**Comment by SnailDove** [comment]
@Jimmuy 我建了一个群 Group ID: 711821078 ，网上有两个deskmini310群，一直加不进去

**Comment by SnailDove** [comment]
> > > > > > "**DESK MINI 可用 睡眠勾选下**" 这个文件夹也一起去替换u盘的efi文件嘛？这个表达没懂
> > > > > 
> > > > > 
> > > > > 在四叶草里不是有个图形界面吗？可以进去勾选下睡眠的选项试下。或者你的型号和版本都一致的话可以直接用我的efi应该也可以的
> > > > 
> > > > 
> > > > 我用你的efi替换黑果小兵的15.4 287的efi 287不行，但是我这边一直下不到etcher可以成功写入的15.2。最后使用了这个[链接](https://github.com/cnsilvan/deskmini310_hackintosh/) 的efi装成功了15.4的Catalina，不过唯一的问题就是睡眠以后需要重新开关机屏幕这样屏幕才能识别，你有什么解决方案吗？。如果可以的话，分享一下你的15.2镜像，笔芯
> > > 
> > > 
> > > 我就是用的小兵的15.2的镜像，就在他的博客可以下的到的
> > 
> > 
> > 好的，谢谢你的反馈，对于睡眠唤醒后屏幕不亮问题（其他都正常），有什么好的建议，或者可能的解决方向去探索吗？ @Jimmuy 有deskmini的机友群吗，嘻嘻？
> 
> 没有群，我也是一个人折腾的，你说的不亮的问题好像我也遇到了，不过我忘记怎么解决的了，你试试hdmi接口和dp接口拔下来再插上去行不行，好像网上可以找到解决方法，你可以找找

HDMI口已经解决，感谢，用hackintool修复fb，然后whatevergreen版本升级1.3.8以后，在添加启动参数即可。
